"""add column to stock model

Revision ID: 0d4f39a6d78d
Revises: 7f68e6984ce6
Create Date: 2025-03-16 15:52:22.287569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d4f39a6d78d'
down_revision: Union[str, None] = '7f68e6984ce6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('minimum_quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock', 'minimum_quantity')
    # ### end Alembic commands ###
