"""Update columns

Revision ID: 189a25e5a8bd
Revises: c93aa8d09387
Create Date: 2025-03-13 22:05:36.744924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '189a25e5a8bd'
down_revision: Union[str, None] = 'c93aa8d09387'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agreement', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('agreement_contract_number_key', 'agreement', type_='unique')
    op.create_index(op.f('ix_agreement_contract_number'), 'agreement', ['contract_number'], unique=True)
    op.create_index(op.f('ix_agreement_id'), 'agreement', ['id'], unique=False)
    op.alter_column('counterparty', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_counterparty_id'), 'counterparty', ['id'], unique=False)
    op.create_index(op.f('ix_counterparty_name'), 'counterparty', ['name'], unique=False)
    op.alter_column('manufacturer', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_manufacturer_name'), 'manufacturer', ['name'], unique=False)
    op.alter_column('products', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('products_name_key', 'products', type_='unique')
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=True)
    op.alter_column('sales', 'date_sold',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('sales', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_sales_id'), 'sales', ['id'], unique=False)
    op.alter_column('stock', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_stock_id'), 'stock', ['id'], unique=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_stock_id'), table_name='stock')
    op.alter_column('stock', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_sales_id'), table_name='sales')
    op.alter_column('sales', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sales', 'date_sold',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.create_unique_constraint('products_name_key', 'products', ['name'])
    op.alter_column('products', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_manufacturer_name'), table_name='manufacturer')
    op.alter_column('manufacturer', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_counterparty_name'), table_name='counterparty')
    op.drop_index(op.f('ix_counterparty_id'), table_name='counterparty')
    op.alter_column('counterparty', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_agreement_id'), table_name='agreement')
    op.drop_index(op.f('ix_agreement_contract_number'), table_name='agreement')
    op.create_unique_constraint('agreement_contract_number_key', 'agreement', ['contract_number'])
    op.alter_column('agreement', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
