"""Change unique constraint on products.name to (name, user_id)

Revision ID: 7f68e6984ce6
Revises: 189a25e5a8bd
Create Date: 2025-03-15 22:25:55.228784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f68e6984ce6'
down_revision: Union[str, None] = '189a25e5a8bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_agreement_contract_number', table_name='agreement')
    op.drop_index('ix_agreement_id', table_name='agreement')
    op.create_unique_constraint(None, 'agreement', ['contract_number'])
    op.drop_index('ix_counterparty_id', table_name='counterparty')
    op.drop_index('ix_counterparty_name', table_name='counterparty')
    op.drop_index('ix_manufacturer_name', table_name='manufacturer')
    op.drop_index('ix_products_id', table_name='products')
    op.drop_index('ix_products_name', table_name='products')
    op.create_unique_constraint('uq_product_name_user', 'products', ['name', 'user_id'])
    op.alter_column('sales', 'date_sold',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index('ix_sales_id', table_name='sales')
    op.drop_index('ix_stock_id', table_name='stock')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index('ix_stock_id', 'stock', ['id'], unique=False)
    op.create_index('ix_sales_id', 'sales', ['id'], unique=False)
    op.alter_column('sales', 'date_sold',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint('uq_product_name_user', 'products', type_='unique')
    op.create_index('ix_products_name', 'products', ['name'], unique=True)
    op.create_index('ix_products_id', 'products', ['id'], unique=False)
    op.create_index('ix_manufacturer_name', 'manufacturer', ['name'], unique=False)
    op.create_index('ix_counterparty_name', 'counterparty', ['name'], unique=False)
    op.create_index('ix_counterparty_id', 'counterparty', ['id'], unique=False)
    op.drop_constraint(None, 'agreement', type_='unique')
    op.create_index('ix_agreement_id', 'agreement', ['id'], unique=False)
    op.create_index('ix_agreement_contract_number', 'agreement', ['contract_number'], unique=True)
    # ### end Alembic commands ###
