"""Added user_id to models

Revision ID: c93aa8d09387
Revises: d9688b7e19a1
Create Date: 2025-03-13 21:49:26.839923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c93aa8d09387'
down_revision: Union[str, None] = 'd9688b7e19a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agreement', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'agreement', 'users', ['user_id'], ['id'])
    op.add_column('counterparty', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'counterparty', 'users', ['user_id'], ['id'])
    op.add_column('manufacturer', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'manufacturer', 'users', ['user_id'], ['id'])
    op.add_column('products', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'users', ['user_id'], ['id'])
    op.add_column('sales', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sales', 'users', ['user_id'], ['id'])
    op.add_column('stock', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stock', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock', type_='foreignkey')
    op.drop_column('stock', 'user_id')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_column('sales', 'user_id')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'user_id')
    op.drop_constraint(None, 'manufacturer', type_='foreignkey')
    op.drop_column('manufacturer', 'user_id')
    op.drop_constraint(None, 'counterparty', type_='foreignkey')
    op.drop_column('counterparty', 'user_id')
    op.drop_constraint(None, 'agreement', type_='foreignkey')
    op.drop_column('agreement', 'user_id')
    # ### end Alembic commands ###
